### ISSUE TITLE
bsg_axil_demux

### ISSUE THREAD

**Issue by Yuan-Mao** [black-parrot-hdk/black-parrot-subsystems#5]
I am not sure if bsg_axil_demux (and maybe bsg_axil_mux as well) can handle multiple outstanding requests properly?

For example, in bsg_axil_demux, after s00 keeps writing data to m00 without getting any bvalid from m00, once m00 sends one bvalid to s00, the m00_wgnt will be cleared. Maybe m00_wgnt should stay high until m00 has sent as many bvalids as the previous write transactions.

**Comment by dpetrisko** [comment]
Yeah seems reasonable -- https://github.com/black-parrot-hdk/black-parrot-subsystems/blob/5904dd769f2a4ebdacd7889e881c8a1c3f5f6dc2/axi/v/bsg_axil_demux.v#L99 could be a fifo instead of a register

**Comment by dpetrisko** [comment]
Fixed with #7
